apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.gateway.name }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.port }}
  type: {{ .Values.gateway.service.type }} 