server:
  port: 9898

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://mysql.microservices.svc.cluster.local:3306/msa_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: msa_user
    password: msa_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true 